### ISSUE TITLE
How the response looks like with ndjson

### ISSUE THREAD

**Issue by 2color** [ipni/caskadht#4]
I understand that one of the nice aspects of ndjson is streaming capability, but when reading this line below the README, I was curious what an example response might look like with ndjson and how it will differ from regular JSON (since with ndjson every line still needs to be valid json)

> steams the results back over ndjson whenever the request Accepts it or regular JSON otherwise.

**Comment by masih** [comment]
Does the verbose `curl` output in [README](https://github.com/ipni/caskadht#run-server-locally) answer your question?

Also note that more response types, like IPFS HTTP delegated routing response, are in the making and will be added to this repo shortly.

**Comment by 2color** [comment]
That's helpful. What would be the same response in JSON?

**Comment by masih** [comment]
It would be the same, except there will be only one such object with one or more items in the `ProviderResults` array.

**Comment by masih** [comment]
More examples are added in #5. Please feel free to reopen if there's anything I might have missed. Thanks
